// <auto-generated />
using Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(ChampionshipContext))]
    [Migration("20230911182813_InsertScoredConcededGoals")]
    partial class InsertScoredConcededGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application.Team", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ConcededGoals")
                        .HasColumnType("int");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("ScoredGoals")
                        .HasColumnType("int");

                    b.Property<string>("TeamCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ConcededGoals = 0,
                            Draws = 11,
                            Losses = 6,
                            ScoredGoals = 0,
                            TeamCity = "Madrid",
                            TeamName = "Real Madrid",
                            Wins = 21
                        },
                        new
                        {
                            ID = 2,
                            ConcededGoals = 0,
                            Draws = 9,
                            Losses = 3,
                            ScoredGoals = 0,
                            TeamCity = "Barcelona",
                            TeamName = "FC Barcelona",
                            Wins = 26
                        },
                        new
                        {
                            ID = 3,
                            ConcededGoals = 0,
                            Draws = 6,
                            Losses = 10,
                            ScoredGoals = 0,
                            TeamCity = "Madrid",
                            TeamName = "Atletico Madrid",
                            Wins = 22
                        },
                        new
                        {
                            ID = 4,
                            ConcededGoals = 0,
                            Draws = 7,
                            Losses = 16,
                            ScoredGoals = 0,
                            TeamCity = "Valencia",
                            TeamName = "Valencia CF",
                            Wins = 15
                        },
                        new
                        {
                            ID = 5,
                            ConcededGoals = 0,
                            Draws = 8,
                            Losses = 13,
                            ScoredGoals = 0,
                            TeamCity = "Seville",
                            TeamName = "Sevilla FC",
                            Wins = 17
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
